### ISSUE TITLE
Licenses under which contributions can be accepted

### ISSUE THREAD

**Issue by dthaler** [l3af-project/governance#1]
The L3AF Technical Charter says that code to run in "the kernel" must be GPL-2.0.  Though it also allows the TSC to accept alternate licenses.

Feedback was previously provided that "the kernel" should at minimum be changed to "the Linux kernel" but that change does not appear to have been done.

This issue is that the governance repo should document the latest TSC policy for licenses.
Example 1) if one wanted an xdp-root program that can run on both Linux and Windows, is the disjunctive "GPL-2.0 OR Apache-2.0" acceptable for a contribution?   What process would one go through? 

Example 2) Should we say that the TSC will only consider OSI Approved Licenses? (https://opensource.org/licenses)

**Comment by vmbrasseur** [comment]
Apparently the charter license change has been done but hasn't yet been uploaded.

@lilluzzi, would it be possible to send a PR with the latest charter (ideally in markdown format) to this repository and then link to it here from the website? Then we can have one canonical version to which we can all refer.

**Comment by vmbrasseur** [comment]
Once #15 is merged then we'll be able to close this issue.

**Comment by vmbrasseur** [comment]
PR merged. This one's done.
