### ISSUE TITLE
Select LFN MAC representative

### ISSUE THREAD

**Issue by vmbrasseur** [l3af-project/governance#13]
Now that L3AF is a sandbox project for LFN, we get to send a representative to the MAC.

Whom shall we send? Who would like to take this on for the community?

**Comment by vmbrasseur** [comment]
@lilluzzi Could we please get a job description for this role?

**Comment by dahavey** [comment]
I would like to be nominated for the MAC representative role. Thank you.

**Comment by jniesz** [comment]
Congrats Daniel for getting nominated.  Closing this issue as we voted to approve this in today's TSC call.
