### ISSUE TITLE
Fix commit permissions

### ISSUE THREAD

**Issue by dthaler** [l3af-project/governance#14]
Require PR to commit, no direct checkins

And make sure CODEOWNERS and the actual permissions to merge match

**Comment by dthaler** [comment]
This is related to issue #6 which is about documenting the process for how to be a committer.
This issue on the other hand is just about enforcement and documenting the current list of committers.

**Comment by jniesz** [comment]
I added a rule to prevent direct commits and now merges are only allowed through PR with 2 approvals for the repos under L3AF project.

**Comment by vmbrasseur** [comment]
Was this just flipping the bit on that setting for the org, or were teams created in the process (or some other access-defining step)?

If the latter, could we please get a list of who's allowed to do what and where?

**Comment by jniesz** [comment]
It was basically adding a branch protection rule to the repo to enforce this.  Committers (write access) are the people that will have access to merge after 2 approvals.
