### ISSUE TITLE
Technical Charter should be added to the repo

### ISSUE THREAD

**Issue by dthaler** [l3af-project/governance#2]
Today the technical charter does not appear to be available publically anywhere I can find.

https://wiki.lfnetworking.org/display/L3AF/L3AF%3A+Technical+Charter%2C+Milestones+and+Deliverables has a title that implies it's there, but it's not.

The wiki also links to https://wiki.lfnetworking.org/display/L3AF/L3AF+Technical+Charter+-+Final?preview=/56068498/56068502/Revised%20L3AF%20Technical%20Charter%206-25-2021.docx%20(1).pdf but that link just gives permission denied.

It should be checked into this repo in a format (e.g., markdown) that makes it easy to propose and review any changes to the technical charter.  LF legal (Scott Nicolas) has already stated that as long as the content is the same, format translations such as to PDF or markdown are fine.

**Comment by vmbrasseur** [comment]
Adding @lilluzzi to the conversation.

If he can get us the PDF, I can pandoc it to markdown then clean it up and add it to the repo.

**Comment by lilluzzi** [comment]
@vmbrasseur I can give you the original July version now or wait for the updated vwersion from LF legal

**Comment by lilluzzi** [comment]
The updated version is added to Goverance repo: https://github.com/l3af-project/governance/blob/main/L3AF%20Technical%20Charter%20February%2016%2C%202022.pdf
And also on the Wiki: https://wiki.lfnetworking.org/pages/viewpageattachments.action?pageId=62489235&metadataLink=true&preview=/62489235/68786169/L3AF%20Technical%20Charter%20February%2016%2C%202022.pdf

**Comment by dalalkaran** [comment]
@sanfern @satyaranjanp - It will be really helpful if you can get this converted into a markup file via a PR.

**Comment by vmbrasseur** [comment]
I reformatted the markdown in the PR and removed the existing PDF to avoid future confusion. Once we can get another review and get it merged, we can close this issue.
