### ISSUE TITLE
Process for selecting maintainers of each repo

### ISSUE THREAD

**Issue by dthaler** [l3af-project/governance#6]
Should document the process for selecting/updating maintainers of each repo

Presumably for new repos (issue #5), the maintainers are approved by the TSC at the time the repo is created.

For existing repos, does adding/removing someone as a maintainer need TSC approval or is that delegated to the existing maintainers of that repo or what?   We should document the answer.

**Comment by jniesz** [comment]
To me it makes sense to designate lead maintainers from the repo to approve adding/removing.

**Comment by dthaler** [comment]
Also need to document who has triage permissions, e.g., to add assignees and labels

**Comment by vmbrasseur** [comment]
#22 is the first pass on a CODEOWNERS file for _this_ repo, but we still need to:

- [ ] Do the same for all the others (l3afd, l3af-arch, eBPF-Package-Repository)
- [ ] Document how to manage (add/remove) people to these files

I'll spin the Triage question off into a different issue so it doesn't block completing this one.

**Comment by vmbrasseur** [comment]
While there are PRs pending to update their CODEOWNERs files, the file _does_ exist in the other repos. That's one step complete.

**Comment by jniesz** [comment]
Initial process for maintainers is merged #29
