### ISSUE TITLE
Who are the TSC members?

### ISSUE THREAD

**Issue by vmbrasseur** [l3af-project/governance#9]
We have open weekly calls, but it's not clear who exactly is a TSC member and who is a community participant.

The [L3AF governance](https://wiki.lfnetworking.org/display/L3AF/Governance) page gives the project a lot of flexibility on this, at least for the first 24 months.

Change the wiki page to point to a markdown file in this repo.

**Comment by dalalkaran** [comment]
FWIU, there is a confluence page that is being used to maintain the list of TSC members. We should update the list if there have been any changes, I just did :) 

https://wiki.lfnetworking.org/pages/viewpage.action?pageId=62491327

**Comment by jniesz** [comment]
Addressed by #30
